name: 删除旧工件

on:
  repository_dispatch:
  workflow_dispatch:
#  schedule:
#    - cron: 0 22 * 11 *

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
    - name: 删除工作流程运行
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 0
