name: 删除旧工件

on:
  repository_dispatch:
  workflow_dispatch:
#  schedule:
#    - cron: 0 22 * 11 *

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    name: 删除旧工件
    strategy:
      fail-fast: false

    steps:
    #- name: Remove old artifacts
    #  uses: c-hive/gha-remove-artifacts@v1
    #  with:
    #     age: '1 month'
         #Optional inputs
         #skip-tags: true
         #skip-recent: 5
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 10
